pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

include ':app'
// Include local WatchRTC SDK module for testing
// include ':watch-rtc-sdk'
// project(':watch-rtc-sdk').projectDir = new File('C:/Users/RahulDarna/Projects/watchRTCSDK-Android-code/watch-rtc-sdk')

